PROMPT == STU_PREF Trigger

--                        123456789012345678901234567890
CREATE OR REPLACE TRIGGER BIU_STU_PREF
BEFORE INSERT OR UPDATE ON  STU_PREF
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  IF INSERTING THEN 
    IF :NEW.PREF_ID IS NULL THEN
      SELECT to_number(sys_guid(),'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
        INTO :NEW.PREF_ID FROM DUAL;
    END IF;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.CREATED_BY := nvl(wwv_flow.g_user,nvl(:NEW.CREATED_BY,USER));
    IF :NEW.PASSWORD_TEMP IS NOT NULL THEN
      :NEW.PASSWORD_ENC := STU_PREF_UTIL.encrypt(P_VALUE => :NEW.PASSWORD_TEMP,
                                                 P_KEY   => :NEW.PREF_ID);
      :NEW.PASSWORD_TEMP:=NULL;
    END IF;
  END IF;

  IF UPDATING THEN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := nvl(wwv_flow.g_user,nvl(:NEW.UPDATED_BY,USER));
    IF :NEW.PASSWORD_TEMP IS NOT NULL THEN
      :NEW.PASSWORD_ENC := STU_PREF_UTIL.encrypt(P_VALUE => :NEW.PASSWORD_TEMP,
                                                 P_KEY   => :NEW.PREF_ID);
      :NEW.PASSWORD_TEMP:=NULL;
    END IF;
  END IF;
 
  -- Increment the revision field
  :NEW.REVISION:=nvl(:OLD.REVISION,0)+1;
 

END;
/

